
CC = gcc

SUPPORT=$(ST_INSTALL_PATH)/lib

EXEC = testPartitioningColoring


all: testColoringPartitioning

testColoringPartitioing: testColoringPartitioning.c
	$(CC) -Wall -pedantic testColoringPartitioning.c -o $(EXEC) -lst-op2

